[2025-04-28 03:34:48,958: INFO/MainProcess] Connected to redis://:**@localhost:6379/0
[2025-04-28 03:34:48,963: INFO/MainProcess] mingle: searching for neighbors
[2025-04-28 03:34:49,978: INFO/MainProcess] mingle: all alone
[2025-04-28 03:34:49,991: INFO/MainProcess] celery@DESKTOP-DEP5S0F ready.
[2025-04-28 03:34:49,994: INFO/MainProcess] Task src.session_service.as_tasks.cleanup_inactive_sessions[9e86eecf-fadf-44b1-8f26-7a2be3f8b0a8] received
[2025-04-28 03:34:50,034: INFO/MainProcess] [{'email': 'john.doe@example.com', 'username': 'john_doe', 'hashed_password': '$2b$12$ni/lsPbDaR4cG500SneuWuPlA04txEf..j046K9QrWDzymD3r1V9e', 'is_superuser': False, 'created_at': '2025-04-28T00:22:40.005337+03:00', 'first_name': 'John', 'last_name': 'Doe', 'id': 4, 'is_active': True, 'updated_at': '2025-04-28T00:22:40.005337+03:00'}]
[2025-04-28 03:34:50,039: INFO/MainProcess] Inactive sessions cleaned up
[2025-04-28 03:34:50,039: INFO/MainProcess] Task src.session_service.as_tasks.cleanup_inactive_sessions[9e86eecf-fadf-44b1-8f26-7a2be3f8b0a8] succeeded in 0.046999999998661224s: None
[2025-04-28 03:35:48,956: INFO/MainProcess] Task src.session_service.as_tasks.cleanup_inactive_sessions[38a889df-db56-450a-8cd1-69226c2f4e94] received
[2025-04-28 03:35:50,987: ERROR/MainProcess] Cleanup error: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /user (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E6FF6FE190>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
[2025-04-28 03:35:50,987: INFO/MainProcess] Task src.session_service.as_tasks.cleanup_inactive_sessions[38a889df-db56-450a-8cd1-69226c2f4e94] succeeded in 2.0310000000026776s: None
